public class Main {
    public static void main(String[] args) {

        String name = "Parth Bonde";

       //int length = name.length();
       //char letter = name.charAt(0);
       //int index = name.indexOf("B");
       // int lastIndex = name.lastIndexOf("n");

        //name = name.toUpperCase();
        //name = name.toLowerCase();
        //name = name.trim();
        //name = name.replace("P", "S");

        /* if(name.isEmpty()){
            System.out.println("Your name is empty");
        }
        else{
            System.out.println("Hello " + name);
        }

        if(name.contains(" ")){
            System.out.println("Your name contains a spaces");
        }
        else{
            System.out.println("Your name DOESN'T containts a spaces");
        } */

        if(name.equals("password")){
            System.out.println("Your name can't be password");
        }
        else{
            System.out.println("Hello " + name);
        }


    }
}