public class Main {

    public static void main(String[] args){
        int age = 20;
        int year = 2025;
        int quantity = 2;

        double price = 19.56;
        double feat = 6.3;
        double temperature = 26.5;

        char grade = 'A';
        char symbol = '@';
        char currency = '$';

        boolean isStudent = true;
        boolean forSeal = false;
        boolean isOnline = true;

        String name = "Parth Bonde";
        String food = "Pizza";
        String email = "fack123@gmail.com";
        String car = "BMW";
        String colore = "Red";


                System.out.println("My age is " + age);
                System.out.println("This year is " + year);
                System.out.println("The quantity of cake is " + quantity);

                System.out.println("The price of book is " + price);
                System.out.println("My height is " + feat );
                System.out.println("Today's temperature is in C " + temperature);

                System.out.println("My grade in last math exam is " + grade );
                System.out.println("The symbol we all have in our email is " + symbol );
                System.out.println("The currency most of the used in all over the world is US Dollar " + currency );

                System.out.println(isStudent);
                System.out.println(forSeal);
                System.out.println(isOnline);

                System.out.println("I'm "+ name);
                System.out.println("My favourite food is " + food);
                System.out.println("My email is " + email);
                System.out.println("I love " + car);
                System.out.println("My fevourite colore is " + colore );
    }
}